name: Build

on: [push, pull_request]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add 'msbuild' to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Add 'premake5' to PATH
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta2"

      - name: Create Project (premake5)
        working-directory: ${{ github.workspace }}
        run: Start-Process -FilePath premake5.exe 'vs2022'

      - name: Build (msbuild)
        working-directory: ${{ github.workspace }}
        run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} project

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "exe"
          path: "build/release/leysourceengineclient.exe"
          retention-days: 3
